package model;

public enum ServerObjectType {
    REGISTER, LOGIN, GET_PROJECT, SET_PROJECT, DELETE_PROJECT, SET_CATEGORY, DELETE_CATEGORY,
    SET_TASK, DELETE_TASK, ADD_USER, DELETE_USER, EXIT_PROJECT, LOGOUT
}
